# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codethink - Web-Entwicklung
email: lukas@codethink.de
description: > # this means to ignore newlines until "baseurl:"
  Web-Entwicklung – Linux Webserver, Wordpress, Static Site Generators
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codethink.de" # the base hostname & protocol for your site
twitter_username: lukhermann
github_username:  lhermann

# SCSS
sass:
  sass_dir: "/"
  # style: compressed

exclude:
    - node_modules

# Build settings
markdown: kramdown

# Plugins
#Autoprefixer is great but takes 2 sec on each build
#Maybe include it into a deploy pipeline with grunt
#gems: [octopress-autoprefixer]
