# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codethink - Web-Engeneering, Front-End Development, SSG
email: lukas@codethink.de
description: > # this means to ignore newlines until "baseurl:"
  Entwicklung langlebiger und nachhaltiger Internetseiten mit neusten Web-Technologien
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codethink.de" # the base hostname & protocol for your site
twitter_username: lukhermann
github_username:  lhermann

# SCSS
sass:
  sass_dir: "/"
  style: compressed # Production

# Speed up jekyll build time
exclude:
    - node_modules
    - serve.sh

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap # Production
  - octopress-autoprefixer # Production (Autoprefixer is great but takes 2 sec on each build)
